spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgre
    password: admin@123456
    url: jdbc:postgresql://192.168.3.10:5433/qing
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
logging:
  level:
    cn.chenyunlong: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
qing:
  api:
    doc-disabled: false
  security:
    white-list:
      - "/admin"
    jwt:
      secret: 123123
      header: jwt
      expiration: 100000
  mp:
    appId: test
    secret: test
    token: test
    aes-key: test
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.chenyunlong.qing.anime.interfaces.rest.v1.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
#seata:
#  application-id:
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 192.168.3.100:8848
#      group: "SEATA_GROUP"
#      namespace: seata
#  tx-service-group: default_tx_group
#  service:
#    vgroup-mapping:
#      default_tx_group: default
seata:
  config:
    type: nacos
    nacos:
      server-addr: 192.168.3.100:8848
      namespace:
      group: SEATA_GROUP
      context-path:
      username: nacos
      password: nacos
      data-id: seataServer.properties
