server:
  port: 8080
spring:
  application:
    name: qing-web-service
  graphql:
    graphiql:
      enabled: true
qing:
  api:
    description: QING-WEB-APPLICATION
  security:
    authing:
      auth-login-url-prefix: /api/auth2/authorization
logging:
  level:
    root: info
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: warning
  client:
    ts:
      path: /ts.zip
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: Qing Web Service
          description: Restore the DTO explosion that was eliminated by server-side developers
          version: 1.0
