server:
  port: 8080
spring:
  application:
    name: qing-service-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qing-auth
    password: 123456
    url: jdbc:postgresql://192.168.3.112:5432/qing-auth
  data:
    redis:
      host: 192.168.3.112
      port: 6379
      database: 0
      password: 123456
  rabbitmq:
    host: 192.168.3.112
    username: rabbitmq
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
qing:
  api:
    description: QING-AUTH-SERVICE

jwt:
  secret: qingSecretKey
  expiration: 18000 # 5小时
logging:
  level:
    root: info
