server:
  port: 8080
spring:
  application:
    name: qing-service-auth
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://192.168.3.10:5433/qing
    username: postgres
    password: admin@123456
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.3.11
      database: 0
      port: 6379
qing:
  api:
    description: QING-AUTH-SERVICE
  security:
    authing:
      auth-login-url-prefix: /api/auth2/authorization

jwt:
  secret: qingSecretKey
  expiration: 18000 # 5小时
logging:
  level:
    root: info
